### PR TITLE
lttng-modules: This change can be removed safely

### PR DESCRIPTION
**Pull request by sharidas**
OE-Core has moved to lttng-modules 2.8 version.
As a result the file name is also changed from
lttng-events.h to lttng-tracepoint-event-impl.h as
per the commit:
451e462fd569ebb0cdd07c60cec11dc184f44feb

The changes mentioned in 0001-Fix-ctf_string-should-handle-NULL-pointers.patch
are available in lttng-tracepoint-event-impl.h.

Signed-off-by: Sujith Haridasan <Sujith_Haridasan@mentor.com>

### CODE REVIEW

**Comment by sharidas** [comment]
@Noor-Ahsan @skrishnakar @kergoth Kindly review my change.

**Comment by Noor-Ahsan** [comment]
we haven't done the layer update so we will merge this when we have latest changes in our poky

**Comment by sharidas** [comment]
@Noor-Ahsan Sure.

**Comment by abelal** [comment]
@Noor-Ahsan, this is required now as https://github.com/MentorEmbedded/mel-manifest/pull/364 is merged.

**Comment by Noor-Ahsan** [comment]
@abelal we are on it

**Pull request merged**
