### PR TITLE
u-boot-ls1: Switch to latest u-boot for LS1021X

### PR DESCRIPTION
**Pull request by arun-khandavalli**
u-boot for ls1021x has been updated to 2015.01 rcu stall crash
has been resolved with a patch to fix the timer compare value
which is causing frequent lockup and crashes in kernel.

Sd-card,lpuart and nor flash u-boot shall be compiled and has been
verified on the target.

Console-Information:

SD-Card: ttyS0 ( JumperSetting J19-J20: 2-3)
NOR    : ttyS0 ( JumperSetting J19-J20: 2-3)
LPUART : ttyLP0 ( JumperSetting J19-J20: 1-2)

RCW Information:

SD-card: No rcw required
NOR    : rcw_1000.bin
LPUART : rcw_1000_lpuart.bin

Switch Setting:

SD-Boot: SW2.1-OFF SW2.3-ON
NOR    : SW2.1-ON  SW2.3-OFF

Signed-off-by: arun-khandavalli <arun_khandavalli@mentor.com>

### CODE REVIEW

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan @skrishnakar : Can you please help in reviewing the commit?

**Comment by skrishnakar** [comment]
Looks good. Thanks!

**Comment by Noor-Ahsan** [comment]
why we are not using meta-fsl-arm u-boot recipe u-boot-ls1_2015.01.bb. The upstream recipe and our recipe has some minor diffs. I think we can control them via bbappend

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan : upstream recipe does only nor config compilation, here we build for nor,lpuart and sdcard u-boot compilation. we have our patch also which will resolve the rcu stall crash. W.r.t sd-card u-boot it has to be renamed to u-boot.bin from u-boot-spl-pbl.bin. Hence i thought it would be good to use our recipe only.

**Comment by Noor-Ahsan** [comment]
Try to set UBOOT_CONFIG = "nor, sdcard, lpuart" in bbappend and see whether it compiles all three u-boot or not. You can also add patch in bbappend.

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan @skrishnakar : I have taken care of review comments, can u please help in reviewing the latest changes.

**Comment by skrishnakar** [comment]
This looks much better. Thanks for the re-work !

**Pull request merged**
