### PR TITLE
busybox: fix "pidof -s" command support

### PR DESCRIPTION
**Pull request by sbobade**
this patch provide fix for "pidof -s"
support by updating necessary busybox cfg.

JIRA: SB-6337

Signed-off-by: Shrikant Bobade <shrikant_bobade@mentor.com>

### CODE REVIEW

**Comment by sbobade** [comment]
@Noor-Ahsan @skrishnakar 
please review and merge, thanks!

**Comment by kergoth** [comment]
I'm not seeing anything in the commit message or elsewhere indicating *why*  this is needed.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Wed, Nov 25, 2015 at 5:31 AM -0800, "Noor-Ahsan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #621<https://github.com/MentorEmbedded/meta-mentor/pull/621>.

**Comment by sbobade** [comment]
This patch provide fix for execution of "pidof -s" command. 
added required cfg. for busybox pidof command. 


command execution log prior to PR:
root@mx6q:~# pidof -s
pidof: invalid option -- 's'
BusyBox v1.23.2 (2015-11-17 15:38:32 IST) multi-call binary.

Usage: pidof [NAME]...

root@mx6q:~# 


with the PR we will get the execution of command successful: 

root@mx6q:~# pidof -s
root@mx6q:~#

Thanks!

**Comment by kergoth** [comment]
Yes, and again, that still doesn't specify *why* we need that argument. Is it required for QA scripts?

Sent from Outlook<http://aka.ms/Ox5hz3>




On Wed, Nov 25, 2015 at 6:31 AM -0800, "Shrikant Bobade" <notifications@github.com<mailto:notifications@github.com>> wrote:


This patch provide fix for execution of "pidof -s" command.
added required cfg. for busybox pidof command.

command execution log prior to PR:
root@mx6q:~# pidof -s
pidof: invalid option -- 's'
BusyBox v1.23.2 (2015-11-17 15:38:32 IST) multi-call binary.

Usage: pidof [NAME]...

root@mx6q:~#

with the PR we will get the execution of command successful:

root@mx6q:~# pidof -s
root@mx6q:~#

Thanks!

**Comment by sbobade** [comment]
ok, "pidof -s" command is used by MESA tracing script: ref: http://jira.alm.mentorg.com:8080/browse/SB-6337

Thanks !
Shrikant

**Pull request merged**
