### PR TITLE
ls1: Remove mksdboot script

### PR DESCRIPTION
**Pull request by arun-khandavalli**
From cedar we have moved to wic tool from generating partition
images for layerscape. So mksdboot script shall not be used
any further hence removing the file.

Signed-off-by: arun-khandavalli <arun_khandavalli@mentor.com>

### CODE REVIEW

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan @skrishnakar : kindly review and merge.

**Comment by skrishnakar** [comment]
Looks reasonable! 

@arun-khandavalli  kindly update "setup & boot instructions" accordingly for LS1. 

Thanks!

**Comment by arun-khandavalli** [comment]
Sure I shall make changes to QSG.

**Comment by Noor-Ahsan** [comment]
That might  need another update later because wic image type is about to be merged upstream.

**Comment by arun-khandavalli** [comment]
Yes. it does needs, then the images for the media shall be directly created.

**Pull request merged**
