### PR TITLE
setup-mel: by default only show the latest version for each machine

### PR DESCRIPTION
**Pull request by kergoth**
Also add a `-a` argument to show all versions.

JIRA: SB-7235

### CODE REVIEW

**Comment by kergoth** [comment]
This is currently going against the sumo branch for elm, but would like confirmation on that.

**Comment by Noor-Ahsan** [comment]
I think we introduced setup-mel version. Can you also bump that?

**Comment by kergoth** [comment]
@Noor-Ahsan

**Comment by Noor-Ahsan** [comment]
@abelal you once bump the Version in setup-mel. That was not this one. Can you check which var you bumped.

**Comment by abelal** [comment]
So I believe I bumped the right variable at the wrong place :confused:

I'd suggest that we correct it in the same PR. Also we should probably drop the definition in the recipe altogether as it can be a pitfall...

**Comment by Noor-Ahsan** [comment]
@abelal  can you point which var you modified. share the link.

**Comment by abelal** [comment]
@Noor-Ahsan, here's that: https://github.com/MentorEmbedded/meta-mentor/blob/sumo/meta-mel/mel-support/recipes-core/meta/archive-release.bbappend#L9

**Comment by kergoth** [comment]
Since the previous attempt to bump it didn't actually change the version at all, we shouldn't have to change anything in this PR. Bumping it from 0 to 2 doesn't really help much at this point :) If we weren't going to merge this, then we could bump to 1 in a separate PR, but if we merge this, there isn't much point.

**Comment by Noor-Ahsan** [comment]
Sure. I will merge this.

**Comment by kergoth** [comment]
@Noor-Ahsan, I believe this is good to go.

**Comment by Noor-Ahsan** [comment]
@kergoth  yes. I was just waiting for our current patch release to go out. I want the behavior change from next patch release.

**Pull request merged**
