### PR TITLE
MinnowMAX: linux-yocto: Add git shallow support

### PR DESCRIPTION
**Pull request by skrishnakar**
This adds git shallow mirror tarball support.

Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>

### CODE REVIEW

**Comment by skrishnakar** [comment]
@Noor-Ahsan , @kergoth : kindly review and merge. Thanks!

**Comment by Noor-Ahsan** [comment]
@kergoth  kindly review

**Comment by skrishnakar** [comment]
@kergoth ping

**Comment by kergoth** [comment]
Looks good to me.

**Pull request merged**
