### PR TITLE
[dunfell] rootfs.py: fix for disabling run-postinsts on systemd

### PR DESCRIPTION
**Pull request by abelal**
The rootfs generation mechanism removed sysV style scripts
for the run-postinsts when they were unneeded but misssed
the same case for systemd type systems. This caused the
systemd service to run unnecessarily which can cause
uninteded long booting times on platforms that do not have
enough hardware resources.

Fixes: https://jira.alm.mentorg.com/browse/SB-15658
Signed-off-by: Awais Belal <awais_belal@mentor.com>

### CODE REVIEW

**Comment by abelal** [comment]
Submitted upstream as well: https://lists.openembedded.org/g/openembedded-core/message/149764

**Comment by abelal** [comment]
The relevant portion changed here from the upstream is https://github.com/MentorEmbedded/meta-mentor/pull/1407/files#diff-e52845ea96b9a803bee5659853a9f0986fa47d26cef3f3d746cb2d1b65c30748R257

**Comment by Noor-Ahsan** [comment]
@abelal do it in two commits. first one is initial commit and second commit should bring your change.

**Comment by abelal** [comment]
> @abelal do it in two commits. first one is initial commit and second commit should bring your change.

@Noor-Ahsan, done but somehow this isn't getting picked up from meta-mentor-staging....

**Comment by Noor-Ahsan** [comment]
Saw your comment

**Comment by abelal** [comment]
This is now fixed, missed the init module for extending the path. Doing some runtime tests now.

**Review by kergoth — APPROVED** [review]
LGTM, nicely done.

**Pull request merged**
