### PR TITLE
Fix various yocto layer compat problems

### PR DESCRIPTION
**Pull request by kergoth**
After this, meta-mentor-common, meta-mel, and meta-mel-support pass the
yocto-check-layer tests. All that remains is meta-mentor-staging, and
it's debatable whether we even want to try to get that registered as
a yocto-compliant software layer, given its purpose.

### CODE REVIEW

**Comment by kmccombe** [comment]
Hi Chris

Will this mean we can register the layers as Yocto compatible against various Yocto versions ?

Thanks
Kevin

On Mar 12, 2018, at 9:47 AM, Christopher Larson <notifications@github.com<mailto:notifications@github.com>> wrote:


After this, meta-mentor-common, meta-mel, and meta-mel-support pass the
yocto-check-layer tests. All that remains is meta-mentor-staging, and
it's debatable whether we even want to try to get that registered as
a yocto-compliant software layer, given its purpose.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MentorEmbedded/meta-mentor/pull/1063

Commit Summary

  *   Fix various yocto layer compat problems

File Changes

  *   R meta-mel-support/openembedded-layer/recipes-core/plymouth/plymouth-mel.bb<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-0> (0)
  *   M meta-mel-support/recipes-core/packagegroups/packagegroup-role-nas.bb<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-1> (6)
  *   M meta-mel-support/recipes-core/packagegroups/packagegroup-role-print-server.bb<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-2> (2)
  *   M meta-mel-support/recipes-core/packagegroups/packagegroup-role-router.bb<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-3> (2)
  *   M meta-mel-support/recipes-core/packagegroups/packagegroup-tools-benchmark.bb<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-4> (9)
  *   M meta-mel/conf/distro/include/mel.conf<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-5> (4)
  *   M meta-mel/fsl-ppc/recipes-connectivity/connman/connman_%.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-6> (2)
  *   M meta-mel/recipes-connectivity/connman/connman_%.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-7> (11)
  *   M meta-mel/recipes-connectivity/openssh/openssh_%.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-8> (4)
  *   M meta-mel/recipes-core/initrdscripts/initramfs-boot_1.0.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-9> (8)
  *   M meta-mel/recipes-core/psplash/psplash_git.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-10> (5)
  *   M meta-mel/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-11> (2)
  *   R meta-mentor-staging/mel-support/recipes-bsp/96boards-tools/96boards-tools_%.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-12> (0)
  *   D meta-mentor-staging/recipes-sato/webkit/webkitgtk_%.bbappend<https://github.com/MentorEmbedded/meta-mentor/pull/1063/files#diff-13> (3)

Patch Links:

  *   https://github.com/MentorEmbedded/meta-mentor/pull/1063.patch
  *   https://github.com/MentorEmbedded/meta-mentor/pull/1063.diff

**Comment by kergoth** [comment]
That's the intention, yes, but of course we'll need to verify we're compatible for each stable branch corresponding to each yocto version, presumably. And meta-mentor-staging is still an open question. meta-sourcery/meta-external-toolchain needs to be verified as compatible as well, so we can register those.

**Comment by kergoth** [comment]
Aside: do not merge this yet, I found a couple issues yesterday.

**Comment by kmccombe** [comment]
Hi Chris

I don't think it's important for meta-mentor-staging for the very reasons you state. (at least that is my $0.02..)

Thanks
Kevin

**Comment by abelal** [comment]
@kergoth, how do we check all such things for branches other than master? morty per se.

**Pull request merged**
