### PR TITLE
mel: keep ADE_VERSION numeric

### PR DESCRIPTION
**Pull request by kergoth**
JIRA: SB-6358

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

### CODE REVIEW

**Comment by kergoth** [comment]
Before:
```
$ bb show DISTRO_VERSION SDK_VERSION ADE_VERSION
# ADE_VERSION=${SDK_VERSION}.${DATETIME_SECS}
ADE_VERSION="next+snapshot.1449079584"
# DISTRO_VERSION=next+snapshot-${DATE}
DISTRO_VERSION="next+snapshot-20151202"
SDK_VERSION="next+snapshot"
```

After:
```
$ bb show DISTRO_VERSION SDK_VERSION ADE_VERSION
# ADE_VERSION=${@'0.0' if not all(c in string.letters for c in '${SDK_VERSION}'.split('.')[0]) else '${SDK_VERSION}'}.${DATETIME_SECS}
ADE_VERSION="0.0.1449079389"
# DISTRO_VERSION=next+snapshot-${DATE}
DISTRO_VERSION="next+snapshot-20151202"
SDK_VERSION="next+snapshot"
```

**Comment by Noor-Ahsan** [comment]
@kergoth as a side note what does next+snapshot mean in SDK version? Should we not set it to 2015.12 similarly DISTRO_VERSION

**Comment by Noor-Ahsan** [comment]
why this is only for master not cedar?

**Comment by kergoth** [comment]
This is only  needed for non-numeric distro version, like next+snapshot used for our 'next' release, as is the case on master. Cedar will have the distro version set to 2015.12, and so this is irrelevent, and next+snapshot shows up nowhere there.

**Comment by kergoth** [comment]
Example from cedar after the fix from SB-6351 goes in:
```
$ bb show DISTRO_VERSION SDK_VERSION ADE_VERSION
# ADE_VERSION=${SDK_VERSION}.${DATETIME_SECS}
ADE_VERSION="2015.12.1449074812"
DISTRO_VERSION="2015.12"
SDK_VERSION="2015.12"
```

**Comment by kergoth** [comment]
Fixed/updated to use string.digits, not string.letters, to correct the logic and align with the commit message's claims :)

**Pull request merged**
