### PR TITLE
Implement git repository delivery for MEL

### PR DESCRIPTION
**Pull request by kergoth**
This should not be merged until #1001 and #1000 are merged, as it depends upon those.

### CODE REVIEW

**Comment by kergoth** [comment]
Updated to split back up mel-checkout and the sourced setup script, to avoid shell compatibility issues. Moved mel-checkout into a scripts dir at mel install toplevel, and renamed the toplevel setup-environment back to the name it had when they were merged, setup-mel, which is a more appropriate name given what it does now. Also reworked how we tell mel-checkout to disable extra manifest inclusion to be more clean.

**Comment by kergoth** [comment]
Hold off a bit on merging this, as I'm prepping a couple more manual builds of this for @cp-mentor before we get our automated builds working with it.

**Comment by Noor-Ahsan** [comment]
@kergoth what is the status of this.

**Comment by kergoth** [comment]
I had to split these changes off into a separate layer to test with dogwood/morty, and had to fix a number of issues I ran into with it, so now I'm pulling those changes back into meta-mentor and cleaning up and rebasing and will update the branch at that time, then we can get it merged.

**Comment by kergoth** [comment]
This should be good to go, now.

**Pull request merged**
