### PR TITLE
LS1021: Prepare bootable sd & enable kgdb config

### PR DESCRIPTION
**Pull request by arun-khandavalli**
These patches provide following features for LS1021:

1) Script to prepare bootable SD for the LS1021 target.
2) Enable Kgdb

JIRA: SB-4262, SB-4521.

Signed-off-by: Arun Khandavalli <arun.khandavalli@mentor.com>

### CODE REVIEW

**Comment by arun-khandavalli** [comment]
@skrishnakar : Can you please help in reviewing the patches.

**Comment by kergoth** [comment]
Is this really where you want that script to go? Buried that deeply into meta-mentor? If the user has to run it directly, that's going to lead to a world of pain. I'd suggest the toplevel scripts directory if the user has to execute it themselves, but this is fine otherwise.

**Comment by arun-khandavalli** [comment]
In PPC case they have a smiliar script prepare-meda.sh placed in a similar location, so followed the suit. Can you help in suggesting a better location where this scipt can go.

**Comment by kergoth** [comment]
Yes, in the PPC case it's in the actual layer at toplevel. e.g. meta-fsl-ppc/scripts/, putting it in meta-mentor/meta-mel/fsl-ppc/scripts/ buries it deeply int he directory structure where the user is unlikely ever to find it. I'd suggest meta-mentor/scripts/, next to setup-rh/etc.

**Comment by arun-khandavalli** [comment]
@skrishnakar I have uploaded the new patch set:

1) Following patches are modified according to the review comments:
a) 06b1d38 linux-ls1: Enable kgdb kernel config parameters.
b) 82b2dd4 mksdboot_ls1.sh: Prepare bootable SD for LS1021

2) Following are the new patches:
b03a020 ls1021a-twr: enable autofs kernel config
4a3091a ls1021a-twr: Enable accessing config.gz via proc
06271fa ls1021a-twr: Use latest defconfig for kernel.
a9cea70 ls1021a-twr: Populate rcw by default.
e8b3cf3 ls1021a-twr: Add file systems support for LS1.
be1eb9d ls1021a-twr: Revert to default u-boot config.
06b242e ls1021a-twr: Enable debug info for ls1.

**Comment by skrishnakar** [comment]
@arun-khandavalli The changes looks good.

**Pull request merged**
