### PR TITLE
mel: fall back from wayland to x11 based on vendor support

### PR DESCRIPTION
**Pull request by kergoth**
JIRA: SB-11414

### CODE REVIEW

**Comment by kergoth** [comment]
We indicate what the vendor supports with `MACHINE_FEATURES`, specifically the `x11` and `wayland` features. If neither is present, we use wayland as usual.

**Comment by kergoth** [comment]
The last piece is to actually add x11 to `MACHINE_FEATURES` in meta-mentor-bsp for any vendors which support x11 but not wayland.

**Comment by abelal** [comment]
Great! this is going to help with the AMD BSPs for sure. They aren't planning to move to wayland just yet.

**Comment by kergoth** [comment]
After more testing we'll want to settle on the exact list of x11 packages to include. Right now it includes x11-base, x11-sato, and hwcodecs (though iirc that's empty for some machines due to mel.conf mucking with the hwcodecs variable).

**Comment by abelal** [comment]
@kergoth, @Noor-Ahsan, we do need this for the sumo branch as well.

**Comment by Noor-Ahsan** [comment]
@abelal  thanks for catching it. Yes we need it on sumo.

**Comment by kergoth** [comment]
Will there be an issue opened to track the fix against sumo?

**Comment by Noor-Ahsan** [comment]
Well we can test it under http://jira.alm.mentorg.com:8080/browse/SB-11229 and send a PR on sumo branch

**Pull request merged**
