### PR TITLE
mel: major cleanup and reorganization of mel.conf

### PR DESCRIPTION
**Pull request by kergoth**

### CODE REVIEW

**Comment by Noor-Ahsan** [comment]
I'll merge this after having one successful build in jenkins.

**Comment by kergoth** [comment]
[**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Sep 18, 2015, 7:08 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/547#issuecomment-141461186 "2015-09-18T14:08:34Z - Replied by Github Comment Enhancer"):
> I'll merge this after having one successful build in jenkins.

That's reasonable, thanks. It's also worth noting that this is for JIRA: SB-5490, forgot to mention that when submitting the pull request.

**Comment by Noor-Ahsan** [comment]
@kergoth Can you update this PR. it is showing conflicts. I'll merge it coz we had successful of i.mx6.

**Comment by kergoth** [comment]
@noor

**Pull request merged**
