### PR TITLE
ls1021a: Add alsa utils to the console-image

### PR DESCRIPTION
**Pull request by arun-khandavalli**
Alsa utils which are requied for playback and record is added.

JIRA:SB-4642
Signed-off-by: Arun Khandavalli <arun.khandavalli@mentor.com>

### CODE REVIEW

**Comment by arun-khandavalli** [comment]
@skrishnakar : could you please help in reviewing the patchset

**Comment by skrishnakar** [comment]
Looks good. Thanks!

**Comment by skrishnakar** [comment]
@Noor-Ahsan Please merge this patch.

**Comment by kergoth** [comment]
Alsa should never be unconditionally installed. We have audio/alsa distro and machine features which should control when audio goes into an image. See how audio/alsa is handled in packagegroup-base.bb for example.

**Comment by arun-khandavalli** [comment]
@kergoth : Thanks, I have raised a new PR:https://github.com/MentorEmbedded/meta-mentor/pull/431/commits please help in reviewing the same.

**Pull request merged**
