### PR TITLE
bblayers/dl: add command for dumping license information

### PR DESCRIPTION
**Pull request by abelal**
For OSS approvals we need to provide list of items that are
being built/distributed along with their version and license
information. This now adds a command 'dump-licenses' to
bitbake-layers to aid this requirement.

Signed-off-by: Awais Belal <awais_belal@mentor.com>

### CODE REVIEW

**Comment by Noor-Ahsan** [comment]
@kergoth kindly review this.

**Comment by abelal** [comment]
@kergoth, updated as per suggestion.

**Comment by abelal** [comment]
@kergoth, updated as per suggestion.

**Comment by Noor-Ahsan** [comment]
@kergoth is it good to be merged now?

**Pull request merged**
