### PR TITLE
cve-check.bbclass: Fix build error when fir initramfs image when buil…

### PR DESCRIPTION
**Pull request by Noor-Ahsan**
…t with cve-check.

* When INHERIT += "cve-check" is added in local.conf and we build mel-initramfs-image it
  fails with following error

File: 'oe-core/meta/classes/cve-check.bbclass', lineno: 101, function: cve_check_write_rootfs_manifest
     0097:        link_name = d.getVar("IMAGE_LINK_NAME")
     0098:        manifest_name = d.getVar("CVE_CHECK_MANIFEST")
     0099:        cve_tmp_file = d.getVar("CVE_CHECK_TMP_FILE")
     0100:
 *** 0101:        shutil.copyfile(cve_tmp_file, manifest_name)
     0102:
     0103:        if manifest_name and os.path.exists(manifest_name):
     0104:            manifest_link = os.path.join(deploy_dir, "%s.cve" % link_name)
     0105:            # If we already have another manifest, update symlinks
File: '/usr/lib/python3.8/shutil.py', lineno: 261, function: copyfile
     0257:
     0258:    if not follow_symlinks and _islink(src):
     0259:        os.symlink(os.readlink(src), dst)
     0260:    else:
 *** 0261:        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
     0262:            # macOS
     0263:            if _HAS_FCOPYFILE:
     0264:                try:
     0265:                    _fastcopy_fcopyfile(fsrc, fdst, posix._COPYFILE_DATA)
Exception: FileNotFoundError: [Errno 2] No such file or directory: '...deploy/images/imx6ullevk-mel/mel-initramfs-image-imx6ullevk-mel-20201027144226.rootfs.cve'

 This error occur due to the reason that tmp/deploy/images folder is not created when shutil.copyfile
 function call is executed. That is why /mel-initramfs-image-imx6ullevk-mel-20201027144226.rootfs.cve
 could not be located in tmp/deploy/images folder. Added bb.utils.mkdirhier(deploy_dir) just before
 shutil.copyfile so that tmp/deploy/images/<machine> folder gets created before the function call.

Signed-off-by: ahsann <noor_ahsan@mentor.com>

### CODE REVIEW

**Comment by kergoth** [comment]
@Noor-Ahsan this will be hard to maintain unless you split this into two commits, the first adding the upstream class, with the commit hash where it was added, and then a second commit with your change. This makes it easier to cherry pick the changes against a later updated bbclass, or against upstream for submission.

**Review by kergoth — CHANGES_REQUESTED** [review]
@Noor-Ahsan This will be hard to maintain unless you split this into two commits, the first adding the upstream class, with the commit hash where it was added, and then a second commit with your change. This makes it easier to cherry pick the changes against a later updated bbclass, or against upstream for submission.

**Comment by Noor-Ahsan** [comment]
aahhh good Idea. I will split it into 2. I will be submitting the updatream change also

**Comment by Noor-Ahsan** [comment]
@kergoth  I have  updated the PR and split it into two initial commit and a fix

**Review by kergoth — APPROVED** [review]

**Pull request merged**
