### PR TITLE
cups: obey ldflags

### PR DESCRIPTION
**Pull request by arehman199**
* JIRA: SB-6540

Signed-off-by: Abdur Rehman <abdur_rehman@mentor.com>

### CODE REVIEW

**Comment by arehman199** [comment]
@Noor-Ahsan Kindly review.

**Comment by Noor-Ahsan** [comment]
@kergoth  kindly review. I think this can be done in better way.

**Comment by kergoth** [comment]
Yeah, putting this in EXTRA_OEMAKE would be a better bet. Please try that.

**Comment by arehman199** [comment]
@Noor-Ahsan I've updated the commit and am using EXTRA_OECONF now. Kindly review.
@kergoth Thanks for your input.

**Pull request merged**
