### PR TITLE
cml1-config.bbclass: operate against unpacked configs

### PR DESCRIPTION
**Pull request by kergoth**
JIRA: SB-15328

### CODE REVIEW

**Comment by kergoth** [comment]
*NOTE* This is master, not fir.

**Comment by kergoth** [comment]
@Noor-Ahsan See https://github.com/MentorEmbedded/meta-mentor/pull/1362

**Comment by Noor-Ahsan** [comment]
@abdulkarim17  kindly test it on your side. @abelal you can review also.

**Review by abelal — APPROVED** [review]
I haven't run any tests but this visually looks correct.

**Comment by abdulkarim17** [comment]
Please see this comment
https://jira.alm.mentorg.com/browse/SB-15328?focusedCommentId=746789&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-746789

**Comment by Noor-Ahsan** [comment]
closing this as this does not resolve our problem

**Comment by kergoth** [comment]
I don't think we need to close this. It might not resolve the current issue, but it's a clear weakness in the class, and this request was against master, not fir.

**Pull request closed without merging**
