### PR TITLE
Fixes for setup script error handling

### PR DESCRIPTION
**Pull request by kergoth**

### CODE REVIEW

**Review by abelal — APPROVED** [review]
:+1:

**Comment by abelal** [comment]
We'll need this on kirkstone as well.

**Comment by Noor-Ahsan** [comment]
@kergoth kindly add jira ticket number in commit message

**Comment by abelal** [comment]
@Noor-Ahsan this isn't done against a specific JIRA ticket. @kergoth unearthed these when he was working on SB-19738 which is for a separate issue. I guess this is ok to be merged.

**Comment by kergoth** [comment]
This was migrated to meta-sokol-flex and merged.

**Pull request closed without merging**
