### PR TITLE
Improve 'source' error handling for setup-{mel,environment}

### PR DESCRIPTION
**Pull request by kergoth**
JIRA: EIS-209

### CODE REVIEW

**Review by jnlewis2 — APPROVED** [review]
Approved

**Comment by Noor-Ahsan** [comment]
@kergoth we probabaly have to increae the version of script IU. I think we have soemthing to update the scripts

**Comment by Noor-Ahsan** [comment]
> @kergoth we probabaly have to increae the version of script IU. I think we have soemthing to update the scripts

ahhh that is aready there https://github.com/MentorEmbedded/meta-mentor/pull/1464/commits/4a23b9a22b284c0b9c00caf307d3bbddd670623c

**Comment by kergoth** [comment]
@jnlewis2 Changed this to keep sourcing setup-mel but correct the sourcing check for dunfell. Future releases may switch to not including it, as it's not truly necessary, but that'll be a future draft PR for ginko, not fir. Thanks!

**Comment by kergoth** [comment]
[**@jnlewis2**](https://github.com/jnlewis2) commented on [Apr 12, 2022, 11:16 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1464#issuecomment-1097041262 "2022-04-12T18:16:00Z - Replied by Github Reply Comments"):
> Should we drop the check for KSH? I think some of the rest of the script does not handle ksh, only bash and zsh.

That's a good idea, I doubt oe-core's setup scripts properly support ksh anyway, and I'd like the logic to be the same between setup-mel and setup-environment. I'll make that change. Thanks.

**Comment by kergoth** [comment]
[**@jnlewis2**](https://github.com/jnlewis2) commented on [Apr 12, 2022, 11:16 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1464#issuecomment-1097041262 "2022-04-12T18:16:00Z - Replied by Github Reply Comments"):
> Should we drop the check for KSH? I think some of the rest of the script does not handle ksh, only bash and zsh.

Fixed.

**Comment by kergoth** [comment]
I think this should be ready for review+merge, dropped the ksh bits

**Review by abelal — APPROVED** [review]
:+1:

**Comment by Noor-Ahsan** [comment]
@kergoth although this is quite old PR but can you add Jira IDs in commit messages?

**Comment by kergoth** [comment]
[**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Jul 7, 2022, 4:13 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1464#issuecomment-1177435227 "2022-07-07T11:13:39Z - Replied by Github Reply Comments"):
> @kergoth although this is quite old PR but can you add Jira IDs in commit messages?

It's already there in the commits that address the issue, just not in the tangentally related fixes.

**Comment by kergoth** [comment]
Migrated to https://github.com/MentorEmbedded/meta-sokol-flex/pull/14

**Pull request closed without merging**
