### PR TITLE
Add Windows ADE class to mel.conf

### PR DESCRIPTION
**Pull request by darknighte**
Signed-off-by: Sean Hudson <sean_hudson@mentor.com>

### CODE REVIEW

**Comment by darknighte** [comment]
@Noor-Ahsan, as we discussed, here is the one line change to remove the need to modify the local.conf to support the windows ADE.  Of course, I don't think we should merge this unless @kergoth and @bikrambhola are comfortable doing so.

**Comment by kergoth** [comment]
Looks fine to me. I think we'll want to consolidate and refactor the classes for dogwood, but this looks fine for now. I'll let @Noor-Ahsan handle the merge, given the risks involved with changes at this point in the release cycle.

**Comment by Noor-Ahsan** [comment]
@bikrambhola Can you review this change and give your suggestion on including this. RIght now we have to include populate_win_ade in IMAGE_CLASSES in local.conf for creating ade. After this change it will not be needed. Will you be able to handle the testing if we add it at this point.

**Comment by bikrambhola** [comment]
@Noor-Ahsan I am Ok with the changes. Since the impact is only on build side and not on functionality, we will run an automated build test to confirm. Please merge. Also need to inform @Dolly and @ulaset for corresponding jenkins build script changes and  change to the Doc section accordingly.

**Comment by Noor-Ahsan** [comment]
@darknighte  kindly coordinate with unika to update the doc. We don't need local.conf change now.

**Pull request merged**
