### PR TITLE
Update for the current shallow implementation

### PR DESCRIPTION
**Pull request by kergoth**

### CODE REVIEW

**Comment by kergoth** [comment]
This needs to be merged at the same time as https://github.com/MentorEmbedded/poky/pull/71.

**Comment by Noor-Ahsan** [comment]
@kergoth this is not merging automatically .... Can you update this?

**Comment by kergoth** [comment]
Ah,  yes, this was also adjusting the bits that are now in meta-mentor-bsp. Will do, and will submit another pull req to that layer.

**Comment by kergoth** [comment]
This has been updated.

**Pull request merged**
