### PR TITLE
python3: update recipe to v3.8.11

### PR DESCRIPTION
**Pull request by ssnaaz**
Update python3 recipe from v3.8.2 to latest UPSTREAM version 3.8.11

Link: https://github.com/openembedded/openembedded-core/blob/dunfell/
meta/recipes-devtools/python/python3_3.8.11.bb

Release: FIR Q1 FY21 update-1 release

JIRA-ID: SB-17178

Signed-off-by: Syeda Shagufta Naaz <SyedaShagufta_Naaz@mentor.com>

### CODE REVIEW

**Comment by kergoth** [comment]
I'm not seeing any recipe change here, only copied source files, am I missing something?

**Comment by ssnaaz** [comment]
> I'm not seeing any recipe change here, only copied source files, am I missing something?

Sorry, the recipe file was missed in the commit, kindly find the same.

**Comment by kergoth** [comment]
Why close the PR?

**Comment by ssnaaz** [comment]
@kergoth, @Noor-Ahsan has asked to place the updated python recipe in layer meta-mentor-cve, you can find the PR here - https://stash.alm.mentorg.com/projects/MEL/repos/meta-mentor-cve/pull-requests/38/overview

**Comment by Noor-Ahsan** [comment]
This is already avaiable upstream in dunfell branch so we proabably drop this in next update from meta-mentor-cve layer

**Pull request closed without merging**
