### PR TITLE
bb-determine-layers: use common data for all parsed layer.conf files 

### PR DESCRIPTION
**Pull request by kergoth**
This allows for variable references amongst the layers, particularly from a layer to its dependencies.

JIRA: SB-19738

### CODE REVIEW

**Review by abelal — APPROVED** [review]
LVGTM!

**Comment by abelal** [comment]
This will also be need on kirkstone.

**Comment by Noor-Ahsan** [comment]
@kergoth Jira IDs are missing in commit message

**Comment by kergoth** [comment]
This was migrated to meta-sokol-flex and merged.

**Pull request closed without merging**
