### PR TITLE
tcf-agent: Remove the patch which is not applicable on latest source

### PR DESCRIPTION
**Pull request by arun-khandavalli**
tcf client patch was added in previous release
to resolve the "LDFLAGS warning during QA_PACKAGE stage" but it
is not now applicable on the latest source hence removing the
patch and the bbappend.

Signed-off-by: arun-khandavalli <arun_khandavalli@mentor.com>

### CODE REVIEW

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan @skrishnakar : kindly review and merge.

**Comment by skrishnakar** [comment]
Looks reasonable.

**Comment by Noor-Ahsan** [comment]
do you get QA warning when this patch is removed or it has been fixed in newer version?

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan : This patch is not applicable on the latest source, it dosent apply cleanly and it breaks the build.

**Comment by Noor-Ahsan** [comment]
@arun-khandavalli that I understood. I was asking do we need similar kind of patch to fix QA warning or the new version is not showing the warning.

**Comment by arun-khandavalli** [comment]
@Noor-Ahsan : Yes we need a new patch to fix the QA-warning in the latest source.

**Pull request merged**
