### PR TITLE
Remove files and redirect to new repository

### PR DESCRIPTION
**Pull request by kergoth**
JIRA: SB-19762

### CODE REVIEW

**Comment by abelal** [comment]
@kergoth would it make sense to add the JIRA ID to commit msg?

**Comment by kergoth** [comment]
[**@abelal**](https://github.com/abelal) commented on [Jul 27, 2022, 9:33 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1499#issuecomment-1196986049 "2022-07-27T16:33:25Z - Replied by Github Reply Comments"):
> @kergoth would it make sense to add the JIRA ID to commit msg?

They already have it..

**Review by abelal — APPROVED** [review]

**Comment by abelal** [comment]
> [**@abelal**](https://github.com/abelal) commented on [Jul 27, 2022, 9:33 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1499#issuecomment-1196986049):
> 
> > @kergoth would it make sense to add the JIRA ID to commit msg?
> 
> They already have it..

Sorry I guess I didn't refresh my already opened tab :/

**Comment by kergoth** [comment]
[**@abelal**](https://github.com/abelal) commented on [Jul 28, 2022, 5:19 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1499#issuecomment-1198066973 "2022-07-28T12:19:57Z - Replied by Github Reply Comments"):
> > [**@abelal**](https://github.com/abelal) commented on [Jul 27, 2022, 9:33 AM MST](https://github.com/MentorEmbedded/meta-mentor/pull/1499#issuecomment-1196986049):
> > 
> > > @kergoth would it make sense to add the JIRA ID to commit msg?
> > 
> > They already have it..
> 
> Sorry I guess I didn't refresh my already opened tab :/

No worries, thanks for the review!

**Pull request merged**
