### PR TITLE
Elm: initial toaster support

### PR DESCRIPTION
**Pull request by abelal**
This fixes toaster based builds with the elm installer structure. For details of the patches submitted upstream additionally for this work please see the JIRA ticket below.

JIRA Ticket: INTAMDDET-2413

### CODE REVIEW

**Comment by kergoth** [comment]
This looks rather confused, either broken or just confusing and incorrect variable naming. BUILDDIR is where the build is done, aka where conf/local.conf lives, whichi s also TOPDIR. oe-core is relative to MELDIR, aka COREBASE/.., not TOPDIR/BUILDDIR.

**Comment by abelal** [comment]
@kergoth, thanks for the review.
I believe you are referring to https://github.com/MentorEmbedded/meta-mentor/pull/1110/commits/0044e80c1c8022da795cd5ca72732a2a8258ff0a, right?
With the current installer structure that we're following for elm I think MELDIR/BUILDDIR resolves to the same thing every time or else I might have just missed something. Can you please elaborate a little?

**Comment by kergoth** [comment]
That's the default, yes, but there's nothing preventing the user from creating multiple build directories once setup-mel has run. We probably shouldn't assume they're identical unless we can't avoid it.

**Comment by abelal** [comment]
@kergoth, the script we're modifying here gets run while setup-mel is running so it should be safe but I guess in order to make the intent clear we should update oe-core path resolution to use MELDIR here. I'll update the PR.

**Comment by abelal** [comment]
PR has been updated.

**Pull request merged**
